apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://aiw3-prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 30s
      queryTimeout: 60s
      httpMethod: POST
    version: 1
